
language: python
python: ['2.7', '3.5', '3.6']
matrix:
  include:
  - python: 3.7
    dist: xenial
sudo: false
install: ['pip install tox-travis tox mock pytest pytest-django pytest-cov']
script: ['tox']
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3