language: python
python:
- '2.7'
- '3.5'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install tox-travis, tox, mock, pytest, pytest-django, pytest-cov
script:
- tox
deploy:
  provider: pypi
  user: django-roles-access
  distribution: sdist bdist_wheel
  on:
    tags: true
    repo: django-roles-access
env:
  global:
  - secure: [REDACTED]
  - secure: [REDACTED]